substitutions:
  device_name: "bathroom-light-switch"
  friendly_name: Bouton Salle de bain

  ha_plafonnier_id: light.salle_de_bain_lumieres
  nightlight_room_type: standard

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  device_base: !include packages/device_base.yaml
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml

binary_sensor:
  - platform: homeassistant
    id: plafonnier_state
    entity_id: ${ha_plafonnier_id}
    internal: true
    trigger_on_initial_state: true

tx_ultimate_switch:
  nightlight:
    room_type: ${nightlight_room_type}

  buttons:
    - position: right
      switch_relay: fallback_wifi
      state_sensor: plafonnier_state
      relay:
        id: relay_1
        name: "Relay"
        restore_mode: RESTORE_DEFAULT_ON
        entity_category: diagnostic
        internal: false
      sensor:
        name: "Bouton"
        icon: mdi:gesture-tap
        device_class: motion



