substitutions:
  device_name: breezeway-light
  friendly_name: "Lumière Préau"
  icon: mdi:bulkhead-light
  area: "Jardin"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}  

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml

#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT

light:
  - platform: binary
    name: none
    id: light1
    icon: ${icon}
    output: light_output

output:
  - platform: gpio
    id: light_output
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
      inverted: false

button:
  - platform: restart
    id: restart_1

binary_sensor:
  - platform: status
    id: status_1
    on_press:
      then:
        switch.turn_on: wifi_led_blue
    on_release:
      then:
        switch.turn_off: wifi_led_blue

  - platform: gpio
    id: reset_button
    pin:
      number: 35
      inverted: true
    on_click:
      min_length: 400ms
      max_length: 800ms
      then:
        button.press: restart_1
    on_double_click:
      then:
        light.toggle: light1

  - platform: gpio
    id: input1
    name: "Bouton Terasse"
    pin:
      number: 38
    on_release:
      then:
        light.toggle: light1
    on_press:
      then:
        light.toggle: light1

  - platform: gpio
    id: input2
    name: "Bouton Parking"
    pin:
      number: 39
    on_release:
      then:
        light.toggle: light1
    on_press:
      then:
        light.toggle: light1

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO13
    clock_pin: GPIO14
    latch_pin: GPIO4
    sr_count: 1

switch:
  #- platform: gpio
  #  name: none
  #  id: light1
  #  pin:
  #    sn74hc595: sn74hc595_hub
  #    number: 0
  #    inverted: false

  - platform: gpio
    id: wifi_led_blue
    pin:
      sn74hc595: sn74hc595_hub
      number: 2
      inverted: true

  - platform: gpio
    id: wifi_led_green
    pin:
      sn74hc595: sn74hc595_hub
      number: 3
      inverted: true

  - platform: gpio
    id: wifi_led_red
    pin:
      sn74hc595: sn74hc595_hub
      number: 4
      inverted: true


sensor:
  - platform: adc
    id: temp_voltage1
    pin: GPIO36
    attenuation: auto
  - platform: resistance
    id: temp_resistance1
    sensor: temp_voltage1
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: ntc
    sensor: temp_resistance1
    name: Temperature 1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: 90
        then:
          - light.turn_off: light1

  - platform: adc
    id: temp_voltage2
    pin: GPIO37
    attenuation: auto
  - platform: resistance
    id: temp_resistance2
    sensor: temp_voltage2
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: ntc
    sensor: temp_resistance2
    name: Temperature 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    #on_value_range:
    #  - above: 90
    #    then:
    #      - light.turn_off: light1