substitutions:
  device_name: "ceiling-light-timothee"
  friendly_name: "Plafonnier Timothée"
  area: "Chambre Timothée"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: DEBUG
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:
web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  athom-rgbct-light: !include packages/athom-rgbct-light.yaml