substitutions:
  device_name: "crystal-light"
  friendly_name: "Veilleuse crystal" 
  area: "Chambre Timothée"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name} #.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  level: DEBUG


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml

external_components:
  - source:
      type: git
      url: https://github.com/AntorFr/esphome-addressable-effects
      ref: main
    components: [custom_addressable_effects]

custom_addressable_effects:

globals:
  - id: touch_was_off
    type: bool
    restore_value: no
    initial_value: "false"

  - id: touch_press_ms
    type: uint32_t
    restore_value: no
    initial_value: "0"

  - id: hue
    type: float
    restore_value: no
    initial_value: "0.0"

binary_sensor:
  - platform: esp32_touch
    id: esp32_touch_pad
    name: "Bouton tactile"
    pin: GPIO4
    threshold: 14000

    on_press:
      - lambda: |-
          id(touch_was_off) = !id(ruban_led).current_values.is_on();
          id(touch_press_ms) = millis();

      - if:
          condition:
            lambda: 'return id(touch_was_off);'
          then:
            # OFF -> on allume (sans forcer RGB, pour restaurer la dernière couleur)
            - light.turn_on:
                id: ruban_led
                effect: "None"
            # OFF + maintien -> cycle couleurs (après un délai dans le script)
            - script.execute: rgb_cycle_while_held
          else:
            # ON -> on ne fait RIEN au press (sinon maintien éteint)
            - lambda: |-
                // no-op

    on_release:
      # stoppe le cycle si on l'avait démarré
      - script.stop: rgb_cycle_while_held

      # si la lampe était ON au départ : tap court = toggle, maintien = rien
      - if:
          condition:
            lambda: |-
              uint32_t held = millis() - id(touch_press_ms);
              return (!id(touch_was_off)) && (held < 350);
          then:
            - light.toggle: ruban_led

      - lambda: |-
          id(touch_was_off) = false;


esp32_touch:
  setup_mode: false
  measurement_duration: 0.25ms
  sleep_duration: 0.5ms

light:
  - platform: esp32_rmt_led_strip
    name: none
    id: ruban_led
    pin: GPIO16
    num_leds: 20       
    chipset: WS2812
    rgb_order: GRB
    restore_mode: RESTORE_DEFAULT_OFF

    effects:
      - addressable_twinklefox:
          name: "TwinkleFox Party"
          palette: party_colors
      - addressable_twinklefox:
          name: "TwinkleFox Snow"
          palette: snow_colors
          twinkle_speed: 3
      - addressable_color_twinkles:
          name: "Color Twinkles"
          palette: rainbow_colors
      - addressable_stars:
          name: "Stars"
          stars_probability: 10%
      - addressable_christmas:
          name: "Christmas"
          bit_size: 1
          blank_size: 0
        
script:
  - id: rgb_cycle_while_held
    mode: restart
    then:
      # délai pour différencier tap court / maintien
      - delay: 350ms
      - while:
          condition:
            lambda: |-
              return id(touch_was_off) && id(esp32_touch_pad).state;
          then:
            - lambda: |-
                id(hue) += 0.01f;
                if (id(hue) >= 1.0f) id(hue) -= 1.0f;

                float h = id(hue) * 6.0f;
                int i = (int) h;
                float f = h - i;
                float p = 0.0f;
                float q = 1.0f - f;
                float t = f;

                float r=0,g=0,b=0;
                switch (i % 6) {
                  case 0: r=1; g=t; b=p; break;
                  case 1: r=q; g=1; b=p; break;
                  case 2: r=p; g=1; b=t; break;
                  case 3: r=p; g=q; b=1; break;
                  case 4: r=t; g=p; b=1; break;
                  case 5: r=1; g=p; b=q; break;
                }

                auto call = id(ruban_led).turn_on();
                call.set_transition_length(0);
                call.set_effect("None");
                call.set_rgb(r, g, b);
                call.perform();
            - delay: 60ms