substitutions:
  device_name: dial-office-desk
  friendly_name: Dial Bureau
  area: Bureau

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area} 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

logger:
  level: DEBUG


# Import packages from GitHub
packages:
  esphome_dial:
    remote_package_files:
      url: https://github.com/antorfr/esphome-dial
      files:
        - packages/m5stack_dial.yaml
        - packages/dial_menu_lvgl.yaml
        - packages/french_fonts.yaml
      ref: main
      refresh: 0s
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

# Import the dial_menu component from GitHub
external_components:
  - source: github://antorfr/esphome-dial@main
    components: [dial_menu, homeassistant_media_player, homeassistant_climate]
    refresh: 0s

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Paris

# === Encoder events for dial_menu ===
sensor:
  - platform: rotary_encoder
    id: !extend dial_encoder
    on_clockwise:
      - lambda: id(menu_controller).on_encoder_rotate(1);
    on_anticlockwise:
      - lambda: id(menu_controller).on_encoder_rotate(-1);

binary_sensor:
  - platform: gpio
    id: !extend dial_button
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 50ms
        then:
          - lambda: id(menu_controller).on_button_click();
      - timing:
          - ON for at least 500ms
        then:
          - lambda: id(menu_controller).on_long_press();

homeassistant_media_player:
  - id: media_player_ma_bureau
    entity_id: media_player.ma_bureau

homeassistant_climate:
  - id: climate_mobile_heater
    entity_id: climate.mobile_heater_plug_thermostat

cover:
  - platform: homeassistant
    id: cover_portail_2
    entity_id: cover.portail_2

# === Test Switches ===
switch:
  - platform: homeassistant
    id: perf_mode
    entity_id: switch.capteur_bureau_mouse_keep_awake
    name: "Mode Perormance"
    internal: True
  - platform: homeassistant
    id: meeting_mode
    entity_id: input_boolean.meeting_mode
    name: "Mode Reunion"
    internal: True
  - platform: homeassistant
    id: iron
    entity_id: switch.office_solder_iron_switch_fer_souder
    name: "Fer à souder" 
    internal: False
  - platform: homeassistant
    id: core_one
    entity_id: switch.office_entry_power_strip_switch_1
    name: "Core One" 
    internal: True
  

  
# === Dial Menu Configuration ===
dial_menu:
  id: menu_controller
  display_id: round_display
  time_id: sntp_time
  idle_timeout: 30s
  language: fr
  font_14: montserrat_fr_14  # Use French fonts
  font_18: montserrat_fr_18
  apps:
    - name: "Focus"
      type: switch
      icon_type: settings
      color: 0x1976D2
      switches:
        - switch_id: perf_mode
          name: "Mode Perormance"
          color: 0x2E7D32
        - switch_id: meeting_mode
          name: "Mode Reunion"
          color: 0x7B1FA2
    - name: "Outils"
      type: switch
      icon_type: power
      color: 0xF57C00
      switches:
        - switch_id: iron
          name: "Fer à souder"
          color: 0xD32F2F
        - switch_id: core_one
          name: "Core One"
          color: 0x0097A7
    - name: "Musique"
      type: media_player
      icon_type: speaker
      color: 0x9C27B0
      media_player_id: media_player_ma_bureau
      volume_step: 0.05
    - name: "Chauffage"
      type: climate
      icon_type: thermostat
      color: 0x03A964
      climate_id: climate_mobile_heater
      temperature_step: 0.5
    - name: "Portail"
      type: cover
      icon_type: gate
      color: 0x577EFF
      cover_id: cover_portail_2
