substitutions:
  device_name: emilie-entrance-switch
  friendly_name: Bouton lumière Émilie
  ha_sleep_sensor: input_boolean.night_mode_emilie
  nightlight_room_type: bedroom


  ha_plafonnier_id: light.chambre_emilie_plafonnier
  ha_clock_id: light.emilie_clock_led_matrix
  ha_prise_bureau_id: switch.chambre_emilie_prise_bureau

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  device_base: !include packages/device_base.yaml
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml


binary_sensor:
  - platform: homeassistant
    id: plafonnier_state
    entity_id: ${ha_plafonnier_id}
    internal: true
    trigger_on_initial_state: true
  - platform: homeassistant
    id: clock_state
    entity_id: ${ha_clock_id}
    internal: true
    trigger_on_initial_state: true
  - platform: homeassistant
    id: prise_bureau_state
    entity_id: ${ha_prise_bureau_id}
    internal: true
    trigger_on_initial_state: true

tx_ultimate_switch:

  buttons:
    - position: right
      switch_relay: false
      state_sensor: plafonnier_state
      relay:
        id: relay_1
        name: "Relay"
        restore_mode: RESTORE_DEFAULT_ON
        entity_category: diagnostic
        internal: false
      sensor:
        name: "Bouton droite"
        icon: mdi:gesture-tap
        device_class: motion
    - position: center
      switch_relay: false
      state_sensor: prise_bureau_state
      sensor:
        name: "Bouton centre"
        icon: mdi:gesture-tap
        device_class: motion
    - position: left
      switch_relay: false
      state_sensor: clock_state
      sensor:
        name: "Bouton gauche"
        icon: mdi:gesture-tap
        device_class: motion


