substitutions:
  device_name: esp-heishamon
  friendly_name: Pompe à challeur Garage
  area: "Garage 1"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  
  comment: HeishaMon v5

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

# Configuration for W5500 Ethernet module
ethernet:
  type: W5500
  clk_pin: GPIO12    # ETH_SPI_SCK
  mosi_pin: GPIO11   # ETH_SPI_MOSI
  miso_pin: GPIO13   # ETH_SPI_MISO
  cs_pin: GPIO10     # ETH_CS
  interrupt_pin: GPIO15  # ETH_IRQ
  reset_pin: GPIO14  # ETH_RST
  clock_speed: 26.67MHz
  use_address: ${device_name}.intra.sberard.fr

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

logger:
  level: DEBUG  # Changez WARN en DEBUG
  logs:
    heishamon: DEBUG
    heishamon.number: DEBUG
    api: DEBUG  # Masquer les erreurs API
    api.connection: DEBUG  # Masquer aussi les erreurs de connexion


web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base_eth: !include packages/device_base_eth.yaml

external_components:
  - source:
      type: git
      url: https://github.com/AntorFr/esphome-heishamon.git
      ref: refactor/modular-architecture
    components: [heishamon]
    refresh: 0s

uart:
  id: heisha_uart
  tx_pin: GPIO17     # TX pin for ESP32
  rx_pin: GPIO18     # RX pin for ESP32
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

heishamon:
  id: heisha_main
  uart_id: heisha_uart
  update_interval: 30s
  listen_only: true
  optional_pcb: false



# SELECT EXAMPLES - 2 selects pour tester
select:
  # 1. Mode d'opération - Read-only basé sur le topic (montre Heat, Cool, DHW, etc.)
  - platform: heishamon
    heishamon_id: heisha_main
    type: "operation_mode"
    name: "Heat Pump Operation Mode"
    id: hp_operation_mode
    
  # 2. Mode de chauffage - Command-based pour contrôle (si pas en listen_only)
  - platform: heishamon
    heishamon_id: heisha_main
    type: "heating_mode"
    name: "Heating Control Mode"
    id: hp_heating_mode