substitutions:
  device_name: esp-assistant-parent
  friendly_name: Atom parents
  area: "Chambre Parents"  

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}  
  name_add_mac_suffix: False

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  #device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  home-assistant-atom: !include packages/home-assistant-atom.yaml

