substitutions:
  device_name: "freezer-plug"
  friendly_name: "Prise Congélateur"
  icon: mdi:fridge-industrial
  current_res: "0.00204"
  voltage_div: "775"

  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  on_boot:
    - switch.turn_on: button_switch

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

#web_server:

logger:
  level: WARN

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  nous-a1t: !include packages/nous-a1t.yaml