substitutions:
  device_name: "freezer-plug"
  friendly_name: "Prise Congélateur"
  # Higher value gives lower watt readout
  current_res: "0.00204"
  # Lower value gives lower voltage readout
  voltage_div: "775"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Nous Smart Wifi Socket A1T (Tasmota)"
  name_add_mac_suffix: false
  project:
    name: "NOUS.Smart-Wifi-Socket"
    version: "A1T"
  on_boot:
    - switch.turn_on: button_switch


esp8266:
  board: esp8285
  restore_from_flash: true
  early_pin_init: false

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr
  fast_connect: on

  ap:
    ssid: ${device_name}
    password: !secret ap_password

captive_portal:

# Enable Web server
web_server:
  port: 80


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time

light:
  - platform: status_led
    id: led
    internal: true
    pin:
      number: GPIO13
      inverted: true

binary_sensor:
  - platform: status
    name: "${friendly_name} - Status"

  # toggle relay on/off
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
    id: "button_state"
    on_press:
      - switch.toggle: "button_switch"

switch:
  - platform: template
    name: "${friendly_name} - Switch"
    icon: mdi:power
    optimistic: true
    id: "button_switch"
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led
  - platform: gpio
    pin: GPIO14
    id: relay

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "${friendly_name} - Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: total_daily_energy
    name: "${friendly_name} - Electric Consumption [kWh]"
    power_id: "nous_a1t_watt"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-clock

  - platform: adc
    pin: VCC
    name: "${friendly_name} - VCC Volt"
    icon: mdi:flash-outline

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s

    current:
      name: "${friendly_name} - Ampere"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac

    voltage:
      name: "${friendly_name} - Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline

    power:
      name: "${friendly_name} - Power"
      id: "nous_a1t_watt"
      unit_of_measurement: W
      icon: mdi:gauge

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} - IP Address"
    ssid:
      name: "${friendly_name} - Wi-Fi SSID"
    bssid:
      name: "${friendly_name} - Wi-Fi BSSID"
  - platform: version
    name: "${friendly_name} - ESPHome Version"
    hide_timestamp: true