substitutions:
  device_name: garage-door-1
  friendly_name: Garage 1

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG

web_server:

#######################################
# Device specific Config Begins Below #
#######################################

packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml
  garage_door: #!include packages/garage_door.yaml 
    url: https://github.com/AntorFr/esphome-projects
    file: packages/garage_door.yaml 

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

switch:
  - platform: gpio
    pin: GPIO16
    id: relay

status_led:
  pin: GPIO23

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s