substitutions:
  device_name: "garage1-ceilling-light"
  friendly_name: "Plafonnier Garage 1"
  area: "Garage 1"
  icon: mdi:bulkhead-light

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
  shelly-1-pm: !include packages/shelly-1pm-gen-4-light.yaml

