substitutions:
  device_name: garage2-ceilling-light
  friendly_name: "Plafonnier Garage 2"
  icon: mdi:bulkhead-light
  area: "Garage 2"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area} 
  platformio_options:
    board_build.f_cpu: 160000000L 

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml


light:
  - platform: binary
    name: none
    id: light1
    icon: ${icon}
    output: light_output

output:
  - platform: gpio
    id: "light_output"
    pin: GPIO26


binary_sensor:
  - platform: gpio
    name: "Switch"
    pin: GPIO4
    on_press:
      then:
        - light.toggle: "light1"
    on_release: 
      then:
        - light.toggle: "light1"
    filters:
      - delayed_on_off: 50ms       
  - platform: gpio
    name: "Button"
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - light.toggle: "light1"
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - light.toggle: "light1"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 12db

  - platform: adc
    name: "Relay Supply Voltage"
    pin: GPIO33
    attenuation: 12db
    filters:
      - multiply: 8

status_led:
  pin:
    number: GPIO0
    inverted: true