substitutions:
  device_name: "garage2-water-tank"
  friendly_name: "Réservoir eau garage 2"
  area: "Garage"




esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  
esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: DEBUG
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

captive_portal:
web_server:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

status_led:
  pin: GPIO23


switch:
  - platform: gpio
    id: 'relay'
    name: "Relay"
    pin: 
      number: GPIO16

sensor:
  - platform: adc
    pin: GPIO36
    name: "raw ADC"
    id: "raw_adc"
    update_interval: 1s
    attenuation: auto
    state_class: "measurement"
    entity_category: "diagnostic"
    on_raw_value:
      then:
        - sensor.template.publish:
            id: water_level
            state: !lambda |- 
              if (x < 0.7) {return NAN; } //sensor disconnected / not powered
              else {return x;}
    
  - platform: template
    name: "Niveau d'eau"
    id: "water_level"
    icon: "mdi:cup-water"
    state_class: "measurement"
    device_class: "volume_storage"
    unit_of_measurement: "L"
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          - 0.75 -> 0.0
          - 2.42 -> 340.0
          - 3.12 -> 650.0