substitutions:
  device_name: garage-3-test
  friendly_name: "garage-3-test"
  area: "Garage 3"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}  

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: ${device_name}.intra.sberard.fr
  use_address: 192.168.10.177

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  level: VERBOSE

web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml

external_components:
  - source:
      type: git
      url: https://github.com/AntorFr/esphome-Hormann
      ref: main  # ou une version spécifique comme v1.0.0
    refresh: 0s
    components: [ hormann_hcp1 ]

status_led:
  pin: GPIO23

uart:
  id: uart_rs485
  tx_pin: GPIO19  # Connect to RX on HW-519 (crossed!)
  rx_pin: GPIO04  # Connect to TX on HW-519 (crossed!)
  baud_rate: 19200
  data_bits: 8
  parity: NONE
  stop_bits: 1

# Hörmann HCP1 component
hormann_hcp1:
  id: hormann
  uart_id: uart_rs485
  # Your HW-519 module has auto-direction (only VCC/GND/TX/RX)
  # No need for de_pin/re_pin - leave them commented out
  # de_pin: GPIO4   # Only needed for modules with DE pin
  # re_pin: GPIO5   # Only needed for modules with RE pin

# Garage door cover entity
cover:
  - platform: hormann_hcp1
    id: garage_door
    name: "Garage Door"
    hormann_hcp1_id: hormann
    device_class: garage

# Garage light
light:
  - platform: hormann_hcp1
    id: garage_light
    name: "Garage Light"
    hormann_hcp1_id: hormann

# Binary sensors for door status
binary_sensor:
  - platform: hormann_hcp1
    hormann_hcp1_id: hormann
    light:
      name: "Light Status"
      id: light_status
    error:
      name: "Error"
      id: error_status
    venting:
      name: "Venting Position"
      id: venting_status
    prewarn:
      name: "Pre-warning"
      id: prewarn_status

# Action buttons
button:
  - platform: hormann_hcp1
    id: impulse_button
    name: "Impulse"
    hormann_hcp1_id: hormann
    action: impulse
    icon: "mdi:gesture-tap"
    
  - platform: hormann_hcp1
    id: venting_button
    name: "Venting Position"
    hormann_hcp1_id: hormann
    action: venting
    icon: "mdi:air-filter"
    
  - platform: hormann_hcp1
    id: emergency_stop_button
    name: "Emergency Stop"
    hormann_hcp1_id: hormann
    action: emergency_stop
    icon: "mdi:stop-circle"
    entity_category: diagnostic

 


    