substitutions:
  device_name: "garden-light-parking2"
  friendly_name: "Lampe Jardin Parking 2"
  light_restore_mode: ALWAYS_ON
  area: "Jardin"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  area: ${area}  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: ${device_name}.intra.sberard.fr
  use_address: "192.168.10.124"

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: DEBUG
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  #device_base: !include packages/device_base.yaml
  athom-rgbct-light: !include packages/athom-rgbct-light.yaml