substitutions:
  device_name: ha-voice-office
  friendly_name: Voice bureau
  area: "Bureau"  

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}  
  name_add_mac_suffix: False

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  home-assistant-voice: !include packages/home-assistant-voice.yaml