substitutions:
  device_name: hallway-light-relay
  friendly_name: "Telerupteur entree"
  area: "Entrée"
  icon: mdi:bulkhead-light

  input1_default_mode: "backup"  # direct / backup / disconnect
  input2_default_mode: "backup"  # direct / backup / disconnect

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}


esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
  shelly-pro-1-pm: !include packages/shelly-pro-1-pm.yaml