substitutions:
  device_name: kitchen-presence-sensor
  friendly_name: capteur cuisine
  area: cuisine

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG
  baud_rate: 0

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

bluetooth_proxy:
  active: true

external_components:
  - source: github://TillFleisch/ESPHome-HLK-LD2450@main


i2c:
  sda: 21
  scl: 22
  scan: true


uart:
  id: uart_bus
  tx_pin: 3
  rx_pin: 1
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  data_bits: 8


sensor:
  - platform: bmp280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    address: 0x76
    update_interval: 60s
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 10s
  - platform: ens160_i2c
    eco2:
      name: "ENS160 eCO2"
    tvoc:
      name: "ENS160 Total Volatile Organic Compounds"
    aqi:
      name: "ENS160 Air Quality Index"
    update_interval: 60s
    address: 0x53
    compensation:
      temperature: id_temperature_sensor
      humidity: id_humidity_sensor
  - platform: aht10
    variant: AHT20
    temperature:
      id: id_temperature_sensor
      name: "Living Room Temperature"
    humidity:
      id: id_humidity_sensor
      name: "Living Room Humidity"
    update_interval: 60s

LD2450:
  uart_id: uart_bus
  max_detection_distance:
    name: "Max Distance"
    initial_value: 4m
  #max_detection_distance: 1.5m
  occupancy:
    name: Occupancy
  targets:
    - target:
        debug: true
        x_position:
            id: t1_xpos
        y_position:
            id: t1_ypos
        speed:
            id: t1_speed
        distance_resolution:
            id: t1_res
        angle:
            id: t1_angle
        distance:
            id: t1_distance

binary_sensor:
  - name: "Mouvement"
    platform: gpio
    pin: GPIO04
    device_class: motion