substitutions:
  device_name: laundry-switch
  friendly_name: Bouton buanderie
  area: "Buanderie"

  ## TX Ultimate ##
  button_count: "1"
  nightlight_sensor_id: "binary_sensor.capteurs_mouvement_bureau"

  nightlight_sleep_id: input_boolean.away_mode

  light_1_internal: "false"
  light_1_entity_category: "config"
  light_1_restore_mode: "RESTORE_DEFAULT_ON" 

  light_2_internal: "true" 
  light_3_internal: "true"

  button_1_switch_relay: "false" 
  button_2_switch_relay: "false"
  button_3_switch_relay: "false"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}  
  project:
    name: smarthomeyourself.tx_ultimate
    version: "1.0"

esp32:
  board: esp32dev
  #framework:
  #  type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  level: INFO

#web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  #tx_ultimate: !include packages/tx_ultimate_debug.yaml

dashboard_import:
  package_import_url: github://SmartHome-yourself/sonoff-tx-ultimate-for-esphome/tx_ultimate.yaml@main
  import_full_config: false

    