substitutions:
  device_name: "laundry-ceiling-light"
  friendly_name: "plafonnier buanderie"
  area: "Buanderie"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: DEBUG
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:
web_server:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

output:
  - platform: ledc
    pin: GPIO05
    id: gpio_5
    inverted: True
  - platform: ledc
    pin: GPIO19
    id: gpio_19

# Example usage in a light
light:
  - platform: color_temperature
    name: None
    color_temperature: gpio_5
    brightness: gpio_19
    cold_white_color_temperature: 5000 K
    warm_white_color_temperature: 2800 K