substitutions:
  device_name: laundry-switch
  friendly_name: Bouton buanderie
  area: "Buanderie"

  ha_light_id: light.laundry_ceiling_light

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

logger: 
  level: DEBUG

packages:
  device_base: !include packages/device_base.yaml
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml

binary_sensor:
  - platform: homeassistant
    id: light_state
    entity_id: ${ha_light_id}
    internal: true
    trigger_on_initial_state: true

tx_ultimate_switch:
  buttons:
    - position: right
      switch_relay: false
      relay:
        id: relay_1
        name: "Relay"
        restore_mode: RESTORE_DEFAULT_ON
        entity_category: diagnostic
        internal: false
      state_sensor: light_state
      sensor:
        name: "Bouton"
        icon: mdi:gesture-tap
        device_class: motion