substitutions:
  device_name: linky
  friendly_name: Linky

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

esp32:
  board: denky_d4
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

captive_portal:

logger:
  level: INFO
  logs:
    teleinfo: ERROR

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

uart:
  id: uart_bus
  rx_pin: GPIO8
  tx_pin: GPIO1
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  update_interval: 30s
  historical_mode: true

time:
  - platform: homeassistant
    timezone: "Europe/Paris"
    id: homeassistant_time

light:
  - platform: neopixelbus
    type: RGB
    variant: SK6812
    pin: GPIO14
    num_leds: 1
    name: "status"
    entity_category: config

#see here for more options: https://gist.github.com/mathieucarbou/886d2a6f5c0b51bb261d6a1329beb08d

sensor:
  # Intensité souscrite
  - platform: teleinfo
    tag_name: "ISOUSC"
    name: "Intensité souscrite"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:current-ac
    entity_category: diagnostic

  # # Index option Base
  #- platform: teleinfo
  #  tag_name: "BASE"
  #  name: "Linky Index Base"
  #  unit_of_measurement: kWh
  #  device_class: energy
  #  state_class: total_increasing
  #  icon: mdi:flash
  #  accuracy_decimals: 2
  #  filters:
  #    - multiply: 0.001
    # Index option HP/HC

  - platform: teleinfo
    tag_name: "HCHC"
    name: "Index HC"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:flash
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "HCHP"
    name: "Index HP"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:flash
    accuracy_decimals: 2
    filters:
      - multiply: 0.001

  # Intensité Instantanée (monophasé)
  - platform: teleinfo
    tag_name: "IINST"
    name: "Intensité Instantanée"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:current-ac

  # Avertissement de Dépassement De Puissance Souscrite
  #- platform: teleinfo
  #  tag_name: "ADPS"
  #  name: "Intensité Instantanée Dépassement"
  #  unit_of_measurement: A
  #  device_class: current
  #  state_class: measurement
  #  icon: mdi:current-ac
  #  entity_category: diagnostic

  # Intensité maximale appelée (monophasé)
  #- platform: teleinfo
  #  tag_name: "IMAX"
  #  name: "Intensité Maximale"
  #  unit_of_measurement: A
  #  device_class: current
  #  state_class: measurement
  #  icon: mdi:current-ac
  #  entity_category: diagnostic

  # Puissance apparente
  - platform: teleinfo
    tag_name: "PAPP"
    name: "Puissance Apparente"
    unit_of_measurement: VA
    state_class: measurement
    device_class: apparent_power
    icon: mdi:gauge

text_sensor:
  # Adresse du compteur
  #- platform: teleinfo
  #  tag_name: "ADCO"
  #  name: "Adresse"
  #  icon: mdi:information
  #  entity_category: diagnostic
  # Option tarifaire choisie
  #- platform: teleinfo
  #  tag_name: "OPTARIF"
  #  name: "Option Tarifaire"
  #  icon: mdi:information
  #  entity_category: diagnostic
  # Période Tarifaire en cours
  - platform: teleinfo
    tag_name: "PTEC"
    name: "Période Tarifaire"
    icon: mdi:information
    filters:
    - substitute:
      - ".. -> "
  # Horaire Heures Pleines Heures Creuses
  - platform: teleinfo
    tag_name: "HHPHC"
    name: "Horaire HP/HC"
    icon: mdi:information
    entity_category: diagnostic
  ## Mot d'état du compteur
  #- platform: teleinfo
  #  tag_name: "MOTDETAT"
  #  name: "Mot d'état"
  #  icon: mdi:information
  ## Présence des potentiels
  #- platform: teleinfo
  #  tag_name: "PPOT"
  #  name: "Présence Potentiels"
  #  icon: mdi:information

