substitutions:
  device_name: livingroom-ble-sensor
  friendly_name: Salon BLE

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    #type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG #ERROR #DEBUG

#web_server:

#######################################
# Device specific Config Begins Below #
#######################################