substitutions:
  device_name: livingroom-presence-sensor
  friendly_name: capteur salon
  area: salon

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area} 

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG
  baud_rate: 0

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml
  ld2410: !include packages/ld2410.yaml

i2c:
  sda: 21
  scl: 22
  scan: true


uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  data_bits: 8


sensor:
  - platform: bmp280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    address: 0x76
    update_interval: 60s
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 10s


binary_sensor:
  - name: "Mouvement"
    platform: gpio
    pin: GPIO04
    device_class: motion