substitutions:
  device_name: timothee-power-strip
  friendly_name: Multiprise Timothée
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

esp8266:
  board: esp8285
  #framework:
  #  type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  level: DEBUG

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  nous-a5t: !include packages/nous-a5t.yaml