substitutions:
  device_name: neopixel-tester
  friendly_name: Pixel tester
   
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  
api:
  reboot_timeout: 5min
  encryption:
    key: !secret api_encryption
  
ota:
  password: !secret ota_password


captive_portal:
web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################

packages:
  device_base: !include packages/device_base.yaml


light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO1
    num_leds: 1
    name: "NeoPixel 1"
    internal: true
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO3
    num_leds: 1
    name: "NeoPixel 3"
    internal: true
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO5
    num_leds: 1
    name: "NeoPixel 5"
    internal: true
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO13
    num_leds: 1
    name: "NeoPixel 13"
    internal: true
    restore_mode: ALWAYS_ON
    