substitutions:
  device_name: neopixel-tester
  friendly_name: Pixel tester
   
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  
api:
  reboot_timeout: 5min
  encryption:
    key: !secret api_encryption
  
ota:
  password: !secret ota_password


captive_portal:
web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################

packages:
  device_base: !include packages/device_base.yaml


light:
  - name: "led_strip"
    platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: D1
    num_leds: 60
   
    