substitutions:
  device_name: neopixel-tester
  friendly_name: Pixel tester
   
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  
api:
  reboot_timeout: 5min
  encryption:
    key: !secret api_encryption
  
ota:
  password: !secret ota_password

external_components:
  #- source: github://AntorFr/esphome-addressable-effetcs
  #  components: [ custom-addressable-effetcs ]
  #  refresh: 1s
  - source:
      type: local
      path: components

custom-addressable-effetcs:  

captive_portal:
web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################

packages:
  device_base: !include packages/device_base.yaml


light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D1
    num_leds: 40
    name: "NeoPixel 1"
    internal: false
    effects:
      - addressable_flicker:
      - addressable_twinkle:
      - addressable_christmas:
          bit_size: 4
          blank_size: 4
      - addressable_stars:
          stars_probability: 30%
    