substitutions:
  device_name: neopixel-tester
  friendly_name: Pixel tester
   
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  
api:
  reboot_timeout: 5min
  encryption:
    key: !secret api_encryption
  
ota:
  password: !secret ota_password

external_components:
  - source: github://AntorFr/esphome-addressable-effetcs@Color-Stars
    components: [ custom-addressable-effetcs ]
    refresh: 1s

custom-addressable-effetcs:  

captive_portal:
web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################

packages:
  device_base: !include packages/device_base.yaml

button:
  - platform: template
    name: "Turn blue"
    on_press:
      then:
        - script.execute: light_blue

light:
  - platform: neopixelbus
    id: leds
    type: GRB
    variant: WS2812
    pin: D1
    num_leds: 40
    name: "NeoPixel 1"
    internal: false
    effects:
      - addressable_flicker:
      - addressable_twinkle:
      - addressable_christmas:
          bit_size: 4
          blank_size: 4
      - addressable_stars:
          stars_probability: 30%
      - addressable_stars:
          name: purple star
          stars_probability: 30%
          color:
            red: 100%
            green: 0%
            blue: 90%

script:
  - id: light_blue
    then:
      - light.turn_on:
          id: leds
          brightness: 100%
          red: 10% 
          green: 10%
          blue:  100%  
