substitutions:
  device_name: nest-mini-bureau
  friendly_name: Nest mini bureau
  area: Bureau

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

ota:
  platform: esphome
  password: !secret ota_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

captive_portal:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  onju-voice: !include packages/onju-voice.yaml

