substitutions:
  device_name: nest-mini-bureau
  friendly_name: Nest mini bureau
  area: Bureau

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

captive_portal:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
  onju-voice: !include packages/onju-voice.yaml

