substitutions:
  device_name: nuki-gateway-kitchen
  friendly_name: Nuki Gateway cuisine
  area: cuisine
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}

esp32:
  board: esp32-poe-iso


#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  use_address: ${device_name}.intra.sberard.fr
#  ap:
#    ssid: ${device_name}
#    password: !secret ap_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  use_address: ${device_name}.intra.sberard.fr
#  use_address: 192.168.10.56

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base_eth.yaml
  #device_base: !include packages/device_base.yaml
  nuki_gateway: !include packages/nuki-gateway.yaml
