substitutions:
  device_name: office-air-sensor
  friendly_name: Bureau qualité air

  presence_sensor_id: binary_sensor.capteurs_mouvement_bureau

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: IKEA LaskaKit

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret ap_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

logger:

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  laskakit: !include packages/laskakit.yaml
