# Read by the Fleet for ESPHome add-on. Do not remove.
# esphome-fleet:
#   tags: day_only

substitutions:
  device_name: "parent-light-switch"
  friendly_name: "Bouton lumière chambre parent"
  area: "Chambre Parents"

  nightlight_room_type: "bedroom"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

packages:
  device_base: !include packages/device_base.yaml
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml

tx_ultimate_switch:
  buttons:
    - position: right
      switch_relay: fallback_wifi
      relay:
        id: relay_1
        name: "Relay"
        restore_mode: RESTORE_DEFAULT_ON
        entity_category: diagnostic
        internal: false
      sensor:
        name: "Bouton"
        icon: mdi:gesture-tap
        device_class: motion



