substitutions:
  device_name: "parent-bed-light"
  friendly_name: "Veilleuse lit parent"
  area: "Chambre Parents"


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: INFO
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:
web_server:

external_components:
  - source:
      type: git
      url: https://github.com/AntorFr/esphome-addressable-effetcs
      ref: dev-new-motifs
    components: [custom_addressable_effects]
    refresh: 0s
  #- source:
  #    type: local
  #    path: components

custom_addressable_effects:
#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

status_led:
  pin: 
    number: D0
    inverted: true

light:
  - name: None
    platform: neopixelbus
    icon: "mdi:light-recessed"
    type: GRB
    variant: WS2812
    pin: D1
    num_leds: 21
    internal: False
    id: led
    restore_mode: ALWAYS_OFF
    effects:
      - addressable_rainbow:
          name: "Halo Arc-en-ciel"
          speed: 2
          width: 3

      - addressable_scan:
          name: "Rotation douce"
          move_interval: 100ms
          scan_width: 1

      - addressable_lambda:
          name: "Respiration"
          update_interval: 100ms
          lambda: |-
            static int step = 0;
            float intensity = (sin(step * 0.1) + 1.0) / 2.0;
            for (int i = 0; i < it.size(); i++) {
              uint8_t r = 255 * intensity;
              uint8_t g = 100 * intensity;
              uint8_t b = 50 * intensity;
              it[i] = Color(r, g, b);
            }
            step++;

      - addressable_lambda:
          name: "Centre pulsant"
          update_interval: 100ms
          lambda: |-
            static int step = 0;
            float intensity = (sin(step * 0.2) + 1.0) / 2.0;
            for (int i = 0; i < it.size(); i++) {
              float distance = abs(i - 10);  // LED centrale
              if (distance < 2) {
                it[i] = Color(255 * intensity, 180 * intensity, 100 * intensity);
              } else {
                it[i] = Color(0, 0, 0);
              }
            }
            step++;

      # ===== STARS EFFECT =====
      - addressable_stars:
          name: "Stars Default"
      - addressable_stars:
          name: "Stars Blue"
          stars_probability: 20%
          color:
            red: 0%
            green: 0%
            blue: 100%
      - addressable_stars:
          name: "Stars Gold"
          stars_probability: 15%
          color:
            red: 100%
            green: 80%
            blue: 0%

      # ===== CHRISTMAS EFFECT =====
      - addressable_christmas:
          name: "Christmas Default"
      - addressable_christmas:
          name: "Christmas Wide"
          bit_size: 3
          blank_size: 1

      # ===== TWINKLEFOX EFFECT =====
      - addressable_twinklefox:
          name: "TwinkleFox Party"
          palette: party_colors
          twinkle_speed: 4
          twinkle_density: 5
      - addressable_twinklefox:
          name: "TwinkleFox Ocean"
          palette: ocean_colors
          twinkle_speed: 3
          twinkle_density: 4
      - addressable_twinklefox:
          name: "TwinkleFox Lava"
          palette: lava_colors
          twinkle_speed: 5
          twinkle_density: 6
      - addressable_twinklefox:
          name: "TwinkleFox Forest"
          palette: forest_colors
          twinkle_speed: 3
          twinkle_density: 4
      - addressable_twinklefox:
          name: "TwinkleFox Rainbow"
          palette: rainbow_colors
          twinkle_speed: 4
          twinkle_density: 5
      - addressable_twinklefox:
          name: "TwinkleFox Snow"
          palette: snow_colors
          twinkle_speed: 3
          twinkle_density: 4
          cool_like_incandescent: false
      - addressable_twinklefox:
          name: "TwinkleFox Holly"
          palette: holly_colors
          twinkle_speed: 4
          twinkle_density: 5
      - addressable_twinklefox:
          name: "TwinkleFox Ice"
          palette: ice_colors
          twinkle_speed: 3
          twinkle_density: 4
      - addressable_twinklefox:
          name: "TwinkleFox Fairy"
          palette: fairy_light
          twinkle_speed: 3
          twinkle_density: 4
          cool_like_incandescent: true
      - addressable_twinklefox:
          name: "TwinkleFox Retro C9"
          palette: retro_c9
          twinkle_speed: 4
          twinkle_density: 5

      # ===== COLOR TWINKLES EFFECT =====
      - addressable_color_twinkles:
          name: "Color Twinkles Cloud"
          palette: cloud_colors
      - addressable_color_twinkles:
          name: "Color Twinkles Rainbow"
          palette: rainbow_colors
          fade_in_speed: 40
          fade_out_speed: 25
      - addressable_color_twinkles:
          name: "Color Twinkles Snow"
          palette: snow_colors
          starting_brightness: 80
      - addressable_color_twinkles:
          name: "Color Twinkles Incandescent"
          palette: incandescent
          fade_in_speed: 20
          fade_out_speed: 10
      - addressable_color_twinkles:
          name: "Color Twinkles Party"
          palette: party_colors
          density: 200
      - addressable_color_twinkles:
          name: "Color Twinkles Ocean"
          palette: ocean_colors
      - addressable_color_twinkles:
          name: "Color Twinkles Forest"
          palette: forest_colors
      - addressable_color_twinkles:
          name: "Color Twinkles Lava"
          palette: lava_colors
          fade_in_speed: 50
          fade_out_speed: 30
