substitutions:
  device_name: pool-filtering-relay
  friendly_name: "Filtration Piscine"
  area: "Piscine"

  relay1_name: "Électrolyse"
  relay1_icon: "mdi:meter-electric"

  relay2_name: "Filtration"
  relay2_icon: "mdi:air-filter"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: ${device_name}.intra.sberard.fr
  use_address: 192.168.10.152


  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
  shelly-pro-2-pm : !include packages/shelly-pro-2-pm.yaml