substitutions:
  device_name: pool-well-relay
  friendly_name: "Puit Piscine"
  area: "Jardin"
  icon: mdi:water-well-outline

  input1_default_mode: "direct"  # direct / backup / disconnect
  input2_default_mode: "direct"  # direct / backup / disconnect

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
  shelly-pro-1-pm: !include packages/shelly-pro-1-pm.yaml

external_components:
  - source: github://AntorFR/esphome-wellpump-guard
    components: [auto_cooldown]
    refresh: 0s

auto_cooldown:
  id: pump_cooldown
  power_sensor: power1
  relay_switch: relay1
  enable_switch:
    name: "Auto Cooldown Enabled"
    restore_mode: RESTORE_DEFAULT_ON
  cooldown_active_sensor:
    name: "Pump Cooldown Active"
    icon: "mdi:timer-off"
  run_minutes_sensor:
    name: "Pump Last Run Minutes"
  pause_minutes_sensor:
    name: "Pump Last Pause Minutes"
  cooldown_remaining_sensor:
    name: "Pump Cooldown Remaining"
  threshold_w: 100.0
  run_min_minutes: 5.0
  run_max_minutes: 60.0
  pause_at_run_min_minutes: 180.0
  pause_at_run_max_minutes: 5.0
  min_restart_pause_minutes: 60.0