substitutions:
  device_name: "pool-water-sensor"
  friendly_name: "Niveau piscine"
  area: "Piscine"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  
  on_boot: 
    then:
      - switch.turn_on: relay

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: DEBUG
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:
web_server:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

status_led:
  pin: GPIO23
switch:
  - platform: gpio
    id: 'relay'
    name: "Relay"
    pin: 
      number: GPIO16

sensor:    
  - platform: adc
    pin: GPIO36
    name: "Niveau d'eau"
    id: "water_level"
    icon: "mdi:cup-water"
    state_class: "measurement"
    device_class: "water"
    update_interval: 1s
    attenuation: auto
    unit_of_measurement: "L"
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.08 -> 100.0
      - multiply: 320
      - sliding_window_moving_average:
          window_size: 60
          send_every: 30
      - timeout: 30s