substitutions:
  device_name: portail-ble-relay
  friendly_name: "Portail Relay BLE"
  area: Jardin

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin:
    number: GPIO12
    ignore_strapping_warning: true
  use_address: ${device_name}.intra.sberard.fr

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password


#web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base_eth.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml


dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/olimex-esp32-poe-iso.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
