substitutions:
  device_name: presence-sensor-shower
  friendly_name: Capteur presence Salle de douche
  area: "Salle de douche"
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  level: DEBUG

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  athom-presence-sensor: !include packages/athom-presence-sensor.yaml