substitutions:
  device_name: restroom-1floor-light
  friendly_name: Bouton toilettes etage 

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

captive_portal:

logger:
  level: DEBUG

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml


binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1

  - platform: gpio
    name: bouton
    pin: GPIO04
    id: switch_1
    #on_press:
    #  then:
    #    - switch.toggle:
    #        id: relay_1
    #on_release:
    #  then:
    #    - switch.toggle:
    #        id: relay_1

  - platform: status
    name: "API Status"
    id: api_status
    internal: True


switch:
  - platform: gpio
    name: switch
    icon: "mdi:lightbulb_outline"
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    name: blueled
    output: blue_led
    internal: true # hides the Blue LED from HomeAssistant