substitutions:
  device_name: shower-light
  friendly_name: lumière douche
  area: salle_de_douche

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG
  baud_rate: 0

#web_server:

#######################################
# Device specific Config Begins Below #
#######################################

packages:
  device_base: !include packages/device_base.yaml

output:
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm1
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm2
  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm3
  - platform: esp8266_pwm
    pin: GPIO04
    frequency: 1000 Hz
    id: pwm4
  - platform: esp8266_pwm
    pin: GPIO05
    frequency: 1000 Hz
    id: pwm5

light:
  - platform: rgbww
    red: pwm5
    green: pwm4
    blue: pwm3
    cold_white: pwm1
    warm_white: pwm2
    color_interlock: True
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    name: None