substitutions:
  device_name: shower-light-switch
  friendly_name: Bouton lumière douche

  ha_spot_douche_id: light.shower_light_lumi_re_douche
  ha_plafonnier_id: light.salle_de_douche_plafonnier

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  device_base: !include packages/device_base.yaml
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml


binary_sensor:
  - platform: homeassistant
    id: ha_spot_douche
    entity_id: ${ha_spot_douche_id}
    internal: true
    trigger_on_initial_state: true
  - platform: homeassistant
    id: plafonnier_state
    entity_id: ${ha_plafonnier_id}
    internal: true
    trigger_on_initial_state: true

tx_ultimate_switch:
  buttons:
    - position: left
      switch_relay: false
      state_sensor: ha_spot_douche
      relay:
        id: relay_1
        name: "Relais spot douche"
        restore_mode: RESTORE_DEFAULT_ON
        entity_category: diagnostic
        internal: false
    - position: center
      switch_relay: false
      state_sensor: plafonnier_state
    - position: right
      switch_relay: true
      relay:
        id: relay_2
        name: "Miroir"
        restore_mode: RESTORE_DEFAULT_OFF
        internal: false




