substitutions:
    device_name: smallcity-train-controler
    friendly_name: Small City - Train controler
  
esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  
api:
  reboot_timeout: 5min
  password: !secret api_password
  
ota:
  password: !secret ota_password

captive_portal:


binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime

#######################################
# Device specific Config Begins Below #
#######################################

  - platform: adc
    pin: 34
    name: "Speed TGV"
    update_interval: 200ms
    attenuation: auto
    unit_of_measurement: '%'
    accuracy_decimals: 0
    filters:
    - calibrate_linear:
        - 0.08 -> -100.0
        - 3.14 -> 100.0
    on_value:
      then:
        - homeassistant.service:
            service: number.set_value
            data:
              value: !lambda |-
                if(abs(x) <= 0) {
                  return 0.0;
                } else {
                  return round(x);
                }
              entity_id: number.vitesse

  - platform: adc
    pin: 32
    name: "Speed TER"
    update_interval: 200ms
    attenuation: auto
    unit_of_measurement: '%'
    accuracy_decimals: 0
    filters:
    - calibrate_linear:
        - 0.08 -> -100.0
        - 3.14 -> 100.0
    on_value:
      then:
        - homeassistant.service:
            service: number.set_value
            data:
              value: !lambda |-
                if(abs(x) <= 0) {
                  return 0.0;
                } else {
                  return round(x);
                }
              entity_id: number.vitesse_2