substitutions:
  device_name: smart-bed-parent
  friendly_name: Lit parents

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

captive_portal:

logger:
  level: INFO

web_server:



#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml
  ld2410: !include packages/ld2410.yaml

binary_sensor:
  - name: "Mouvement gauche"
    platform: gpio
    pin: GPIO26
    device_class: motion
    filters:
      - delayed_off: 5s
  - name: "Mouvement droite"
    platform: gpio
    pin: GPIO33
    device_class: motion
    filters:
      - delayed_off: 5s
  - name: "Presence gauche"
    platform: gpio
    pin:
      number: GPIO17
      inverted: true
      mode:
          input: true
          pullup: true
    filters:
      - delayed_on: 15s
      - delayed_off: 15s
    device_class: occupancy
  - name: "Presence droite"
    platform: gpio
    pin:
      number: GPIO04
      inverted: true
      mode:
          input: true
          pullup: true
    filters:
      - delayed_on: 15s
      - delayed_off: 15s

    device_class: occupancy

status_led:
  pin: GPIO23

light:
  - id: led_gauche
    name: "lumière gauche"
    #icon: "mdi:heart"
    #entity_category: config
    platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO27
    num_leds: 120
    method:
      type: esp32_i2s
      bus: 0
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - pulse:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
  - id: led_droite
    name: "lumière droite"
    #icon: "mdi:heart"
    #entity_category: config
    platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO25
    num_leds: 120
    method:
      type: esp32_i2s
      bus: 1
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - pulse:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker: