substitutions:
  device_name: test-switch
  friendly_name: Bouton test
  ha_sleep_sensor: input_boolean.away_mode
  nightlight_room_type: bedroom
  relay_1_restore_mode: RESTORE_DEFAULT_ON
  relay_2_restore_mode: RESTORE_DEFAULT_ON


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml

tx_ultimate_switch:
  buttons:
    - position: right
      switch_relay: false
      relay: relay_1
      sensor:
        name: "Bouton droite"
        icon: mdi:gesture-tap
        device_class: motion
    - position: center
      switch_relay: false
      relay: relay_2
      sensor:
        name: "Bouton centre"
        icon: mdi:gesture-tap
        device_class: motion


