substitutions:
  device_name: "test"
  friendly_name: "test"
  area: "Buanderie"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}  

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  level: DEBUG
  
api:
  reboot_timeout: 30min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:
web_server:


#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml