substitutions:
  device_name: test
  friendly_name: test

esphome:
  name: test
  friendly_name: test


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

#captive_portal:

logger:
  level: DEBUG
  baud_rate: 0

web_server:

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base:
    url: https://github.com/AntorFr/esphome-projects
    file: packages/device_base.yaml

globals:
  - id: source
    type: std::string
  - id: url
    type: std::string
  - id: info
    type: std::string


light:
  - id: status_led
    name: "status_led"
    internal: False
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO38
    num_leds: 1
    chipset: WS2812
