# Read by the Fleet for ESPHome add-on. Do not remove.
# esphome-fleet:
#   tags: day_only

substitutions:
  device_name: timothee-entrance-switch
  friendly_name: Bouton lumière Timothée

  ha_sleep_sensor: input_boolean.night_mode_timothee
  nightlight_room_type: bedroom

  ha_plafonnier_id: light.ceiling_light_timothee_plafonnier_timoth_e
  ha_clock_id: light.led_matrix
  ha_sous_lit_id: light.timothee_bed_light_lumi_res_lit_timoth_e


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  device_base: !include packages/device_base.yaml
  tx_ultimate_migrated: !include packages/tx_ultimate_migrated.yaml

binary_sensor:
  - platform: homeassistant
    id: plafonnier_state
    entity_id: ${ha_plafonnier_id}
    internal: true
    trigger_on_initial_state: true
  - platform: homeassistant
    id: clock_state
    entity_id: ${ha_clock_id}
    internal: true
    trigger_on_initial_state: true
  - platform: homeassistant
    id: sous_lit_state
    entity_id: ${ha_sous_lit_id}
    internal: true
    trigger_on_initial_state: true

tx_ultimate_switch:
  buttons:
    - position: left
      switch_relay: false
      state_sensor: plafonnier_state
      relay:
        id: relay_1
        name: "Relay"
        restore_mode: RESTORE_DEFAULT_ON
        entity_category: diagnostic
        internal: false
      sensor:
        name: "Bouton gauche"
        icon: mdi:gesture-tap
        device_class: motion
    - position: center
      switch_relay: false
      state_sensor: clock_state
      sensor:
        name: "Bouton centre"
        icon: mdi:gesture-tap
        device_class: motion
    - position: right
      switch_relay: false
      state_sensor: sous_lit_state
      sensor:
        name: "Bouton droite"
        icon: mdi:gesture-tap
        device_class: motion




