substitutions:
  device_name: timothee-wood-pannel
  friendly_name: Timothée bibliotheque
  matrix_led_pin: "15"
   
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

logger:
  
api:
  reboot_timeout: 5min
  encryption:
    key: !secret api_encryption
  
ota:
  platform: esphome
  password: !secret ota_password


captive_portal:

#######################################
# Device specific Config Begins Below #
#######################################

#dashboard_import:
#  package_import_url: github://adonno/tagreader/tagreader.yaml

packages:
  device_base: !include packages/device_base.yaml
  matrix_display: !include packages/matrix_display.yaml
  tag_reader: !include packages/tag_reader.yaml 
  #device_base:
  #  url: https://github.com/AntorFr/esphome-projects
  #  file: packages/device_base.yaml
  #matrix_display:
  #  url: https://github.com/AntorFr/esphome-projects
  #  file: packages/matrix_display.yaml
 
#  tag_reader:
#    url: https://github.com/AntorFr/esphome-projects
#    file: packages/tag_reader.yaml 


