substitutions:
  device_name: underwater-pool-light
  friendly_name: "lumière immergée"
  #icon: mdi:bulkhead-light
  area: "Piscine"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 
  area: ${area}  

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

captive_portal:

logger:
  #level: DEBUG

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
  shelly-pro-1: !include packages/shelly-pro-1_light.yaml
