substitutions:
  device_name: washing-machine-plug
  friendly_name: "Prise Machine à laver"
  icon: mdi:washing-machine
  current_res: "0.00204"
  voltage_div: "775"
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_name}.intra.sberard.fr

  ap:
    ssid: ${device_name}
    password: !secret ap_password

api:
  reboot_timeout: 15min
  encryption:
    key: !secret api_encryption

ota:
  password: !secret ota_password

captive_portal:

web_server:

logger:
  level: DEBUG

#######################################
# Device specific Config Begins Below #
#######################################
packages:
  device_base: !include packages/device_base.yaml
    #url: https://github.com/AntorFr/esphome-projects
    #file: packages/device_base.yaml
  m5stack-atom-echo: !include packages/nous-a1t.yaml