sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime

binary_sensor:
  - platform: status
    name: ${device_name} Status
    entity_category: diagnostic

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${device_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${device_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic