substitutions:
  tx_pin: "1"
  rx_pin: "3"

logger:
  level: DEBUG
  baud_rate: 0

uart:
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  parity: NONE
  stop_bits: 1
  baud_rate: 256000

ld2410:

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
      internal: true
      restore_mode: RESTORE_DEFAULT_OFF
      entity_category: config
    bluetooth:
      name: "control bluetooth"
      internal: true
      restore_mode: RESTORE_DEFAULT_OFF
      entity_category: config

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      device_class: occupancy
    has_moving_target:
      name: Moving Target
      device_class: motion
    has_still_target:
      name: Still Target
      device_class: occupancy

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance


