substitutions:
  ikea_light_relay: "relay_1"

button:
  - platform: template
    name: "Reset Ikea"
    on_press:
      - script.execute: reset_ikea

script:
  - id: reset_ikea
    mode: restart
    then:
      - repeat:
          count: 6
          then:
            - light.turn_off:
                id: ${ikea_light_relay}
            - delay: 800ms
            - light.turn_on:
                id: ${ikea_light_relay}
            - delay: 800ms