esphome:
  on_boot:
    priority: -100
    then:
      - script.execute: led_update

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - script.execute: led_update
  on_disconnect:
    then:
      - script.execute: led_update

api:
  on_client_connected:
    then:
      - script.execute: led_update
  on_client_disconnected:
    then:
      - script.execute: led_update

#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT

light:
  - platform: binary
    name: none
    id: light1
    #icon: ${icon}
    output: light_output

output:
  - platform: gpio
    id: light_output
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
      inverted: false

button:
  - platform: restart
    id: restart_1

binary_sensor:
  - platform: gpio
    id: reset_button
    pin:
      number: 35
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - button.press: restart_1
      - timing: 
          - ON for 5s to 10s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - button.press: restart_1
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: light1

  - platform: gpio
    id: input1
    name: "Bouton 1"
    disabled_by_default: true
    pin:
      number: 38

  - platform: gpio
    id: input2
    name: "Bouton 2"
    disabled_by_default: true
    pin:
      number: 39

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO13
    clock_pin: GPIO14
    latch_pin: GPIO4
    sr_count: 1

switch:
  #- platform: gpio
  #  name: none
  #  id: light1
  #  pin:
  #    sn74hc595: sn74hc595_hub
  #    number: 0
  #    inverted: false

  - platform: gpio
    id: wifi_led_blue
    pin:
      sn74hc595: sn74hc595_hub
      number: 2
      inverted: true

  - platform: gpio
    id: wifi_led_green
    pin:
      sn74hc595: sn74hc595_hub
      number: 3
      inverted: true

  - platform: gpio
    id: wifi_led_red
    pin:
      sn74hc595: sn74hc595_hub
      number: 4
      inverted: true


sensor:
  - platform: adc
    id: temp_voltage1
    pin: GPIO36
    attenuation: auto
  - platform: resistance
    id: temp_resistance1
    sensor: temp_voltage1
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: ntc
    sensor: temp_resistance1
    name: Temperature 1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: 90
        then:
          - light.turn_off: light1

  - platform: adc
    id: temp_voltage2
    pin: GPIO37
    attenuation: auto
  - platform: resistance
    id: temp_resistance2
    sensor: temp_voltage2
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: ntc
    sensor: temp_resistance2
    name: Temperature 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    #on_value_range:
    #  - above: 90
    #    then:
    #      - light.turn_off: light1

script:
  - id: led_off
    then:
      - switch.turn_off: wifi_led_red
      - switch.turn_off: wifi_led_green
      - switch.turn_off: wifi_led_blue

  - id: led_red
    then:
      - script.execute: led_off
      - switch.turn_on: wifi_led_red

  - id: led_green
    then:
      - script.execute: led_off
      - switch.turn_on: wifi_led_green

  - id: led_blue
    then:
      - script.execute: led_off
      - switch.turn_on: wifi_led_blue

  - id: led_update
    then:
      - if:
          condition:
            api.connected:
          then:
            - script.execute: led_blue
          else:
            - if:
                condition:
                  wifi.connected:
                then:
                  - script.execute: led_green
                else:
                  - script.execute: led_red