substitutions:
  icon: mdi:bulkhead-light

esphome:
  name: shelly-1pm-gen-4

esp32:
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

#web_server:

uart:
  id: bl0942_uart
  tx_pin: GPIO6
  rx_pin:
    number: GPIO7
    mode:
      pullup: true
      input: true
  baud_rate: 9600
  stop_bits: 1

output:
  - id: relay_output
    platform: gpio
    pin: GPIO4

light:
  - platform: binary
    name: none
    id: light1
    icon: ${icon}
    output: relay_output

sensor:
  - id: temperature
    name: Temperature
    platform: ntc
    sensor: temperature_sensor_resistance
    icon: mdi:thermometer
    entity_category: diagnostic
    unit_of_measurement: °C
    accuracy_decimals: 1
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 25°C
  - id: temperature_sensor_resistance
    platform: resistance
    sensor: temperature_sensor_voltage
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - id: temperature_sensor_voltage
    platform: adc
    pin: GPIO3
    attenuation: 12db

  - platform: bl0942
    uart_id: bl0942_uart
    update_interval: 1s
    line_frequency: 60Hz
    voltage:
      name: Voltage
      id: sensor_voltage
      entity_category: diagnostic
    current:
      id: sensor_current
      name: current
    power:
      name: Power
      id: sensor_power
    frequency:
      name: Frequency
      id: sensor_frequency
      accuracy_decimals: 2
      entity_category: diagnostic
    energy:
      name: Energy
      id: sensor_energy
      entity_category: diagnostic
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 3

binary_sensor:
  # - id: shelly_add_on_digital_in
  #   name: addon digital in
  #   disabled_by_default: true
  #   platform: gpio
  #   pin: GPIO12
  #   filters:
  #     - delayed_off: 50ms

  # - id: shelly_add_on_data
  #   name: addon data
  #   disabled_by_default: true
  #   platform: gpio
  #   pin: GPIO16
  #   filters:
  #     - delayed_off: 50ms

  # - id: shelly_add_on_analog_in
  #   name: addon analog in
  #   disabled_by_default: true
  #   platform: gpio
  #   pin: GPIO17
  #   filters:
  #     - delayed_off: 50ms

  - id: shelly_1pm_gen4_switch
    name: Switch
    platform: gpio
    pin: GPIO10
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: "light1"
    on_release: 
      then:
        - light.toggle: "light1"

  - id: shelly_1pm_gen4_button
    name: Button
    platform: gpio
    pin: GPIO1
    entity_category: diagnostic
    filters:
      - delayed_off: 50ms

  - id: error_overtemp
    name: Overheating
    device_class: problem
    entity_category: diagnostic
    platform: template
    condition:
      any:
        - binary_sensor.is_on: error_overtemp # Latch ON
        - sensor.in_range:
            id: temperature
            above: 75.0
    on_press:
      then:
        - light.turn_off: light1

  - id: error_overpower
    name: Overpowering
    device_class: problem
    entity_category: diagnostic
    platform: template
    condition:
      any:
        - binary_sensor.is_on: error_overpower # Latch ON
        - for:
            time: 1s
            condition:
              sensor.in_range:
                id: sensor_current
                above: 16 # This is model specific!
    on_press:
      then:
        - light.turn_off: light1

status_led:
  pin:
    number: GPIO0
    inverted: true