substitutions:
  icon: "mdi:power"
  restore_mode: RESTORE_DEFAULT_OFF

esp8266:
  board: esp8285
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "None"
    icon: ${icon}
    pin: GPIO12
    id: relay
    restore_mode: ${restore_mode}

status_led:
  pin:
    number: GPIO13
    inverted: yes

        