substitutions:
  light_name: "switch"
  light_icon: "mdi:lightbulb"
  light_restore_mode: "RESTORE_DEFAULT_OFF"
  light_entity_category: "config"
  light_controled: "false" #controled by the button
  light_switch_always_on: "true" #switch always on 

esp8266:
  board: esp8285
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle:
          id: relay_1

  - platform: gpio
    name: bouton
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - script.execute: toggle
    on_release:
      then:
        - script.execute: toggle

  - platform: status
    name: "API Status"
    id: api_connected
    internal: True
    filters:
     - delayed_off: 30s
    on_press:
      - script.execute: api_reconnected

output:
  - id: output_1
    platform: gpio
    pin: GPIO12

light:
  - id: relay_1
    platform: binary
    name: ${light_name}
    icon: ${light_icon}
    restore_mode: ${light_restore_mode}
    output: output_1
    entity_category: ${light_entity_category}

status_led:
  pin:
    number: GPIO13
    inverted: true

script:
  - id: api_reconnected
    mode: restart
    then:
      - if:
          condition:
            lambda: "return (${light_switch_always_on});"
          then:
            - light.turn_on:
                id: relay_1

  - id: toggle
    mode: restart
    then:
      - if:
          condition:
            lambda: "return (${light_controled} || !(id(api_connected).state));"
          then:
            - light.toggle:
                id: relay_1
        