substitutions:
  icon: "mdi:power"

esp8266:
  board: esp8285

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "None"
    icon: ${icon}
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

        